### ISSUE TITLE
Feature: Certificate for HTTPS

### ISSUE THREAD

**Issue by ZTHawk** [tronikos/home-assistant-addons#8]
For HTTPS it would be helpful to have the possiblility to define a certificate location (eg: like in "Node Red").
Right now I see certificate issues when accessing the page (especially when using an iframe in HA).

**Comment by tronikos** [comment]
openspeedtest allows certificates, see "How to Use Your Own Secure Sockets Layer (SSL) Certificate, Self-Signed or Paid?" at https://hub.docker.com/r/openspeedtest/latest but since I'm using their official docker image as the image of the addon, I can't do that. I'd have to create my own Dockerfile to allow defining the certificate location in a Home Assistant directory but I don't want to manage building and releasing a docker image. Right now the addon is just a yaml file that wraps the official image as addon and I want to keep it that way for simplicity.

**Comment by Steffen06** [comment]
@tronikos you don't  need to create your own docker image! You can map the ssl dir with 
```
map:
  - type: ssl
    read_only: False
    path: /etc/ssl
``` 
in the [config.yaml](https://github.com/tronikos/home-assistant-addons/blob/main/openspeedtest/config.yaml) (see [Add-on configuration | Home Assistant Developer Docs](https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-configuration)) The only downside to this approach is that you then need to specify `nginx.crt` and `nginx.key` in th HA ssl dir with read access to the files for the user in the container. Without these files, the add-on will not start.
